version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    labels:
      - "traefik.enable=true"

  website:
    image: 475365909498.dkr.ecr.us-east-2.amazonaws.com/website:latest
    container_name: portfolio-website
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`localhost`) || PathPrefix(`/`)"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.services.website.loadbalancer.server.port=80" 
